
$('.portfoll').owlCarousel({
    loop:true,
    margin:30,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        320:{
            items:2,
            margin:10,
            nav:true
        },
        426:{
            items:2,
            nav:true,
            loop:true
        },
        993:{
            items:2,
            nav:true,
            loop:true
        },
        1100:{
            items:2,
            nav:true,
            loop:true
        }
    }
})
$('.reviews').owlCarousel({
    loop:true,
    margin:40,
    nav:true,
    responsive:{
        0:{
            items:1,
            nav:true,
        },
        600:{
            items:2,
            nav:true,
        },
        1000:{
            items:4,
            width:255,
            nav:true,
        }
    }
})

